//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:18 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.impl.v4_4;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}KohonenMap" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}NUM-ARRAY" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Partition" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Covariances" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"extension", "kohonenMap", "numarray", "partition", "covariances"})
@XmlRootElement(name = "Cluster")
public class Cluster {

  @XmlElement(name = "Extension")
  protected List<Extension> extension;

  @XmlElement(name = "KohonenMap")
  protected KohonenMap kohonenMap;

  @XmlElement(name = "NUM-ARRAY")
  protected NUMARRAY numarray;

  @XmlElement(name = "Partition")
  protected Partition partition;

  @XmlElement(name = "Covariances")
  protected Covariances covariances;

  @XmlAttribute(name = "id")
  protected String id;

  @XmlAttribute(name = "name")
  protected String name;

  @XmlAttribute(name = "size")
  @XmlSchemaType(name = "nonNegativeInteger")
  protected BigInteger size;

  /**
   * Gets the value of the extension property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extension property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Extension }
   */
  public List<Extension> getExtension() {
    if (extension == null) {
      extension = new ArrayList<Extension>();
    }
    return this.extension;
  }

  /**
   * Gets the value of the kohonenMap property.
   *
   * @return possible object is {@link KohonenMap }
   */
  public KohonenMap getKohonenMap() {
    return kohonenMap;
  }

  /**
   * Sets the value of the kohonenMap property.
   *
   * @param value allowed object is {@link KohonenMap }
   */
  public void setKohonenMap(KohonenMap value) {
    this.kohonenMap = value;
  }

  /**
   * Gets the value of the numarray property.
   *
   * @return possible object is {@link NUMARRAY }
   */
  public NUMARRAY getNUMARRAY() {
    return numarray;
  }

  /**
   * Sets the value of the numarray property.
   *
   * @param value allowed object is {@link NUMARRAY }
   */
  public void setNUMARRAY(NUMARRAY value) {
    this.numarray = value;
  }

  /**
   * Gets the value of the partition property.
   *
   * @return possible object is {@link Partition }
   */
  public Partition getPartition() {
    return partition;
  }

  /**
   * Sets the value of the partition property.
   *
   * @param value allowed object is {@link Partition }
   */
  public void setPartition(Partition value) {
    this.partition = value;
  }

  /**
   * Gets the value of the covariances property.
   *
   * @return possible object is {@link Covariances }
   */
  public Covariances getCovariances() {
    return covariances;
  }

  /**
   * Sets the value of the covariances property.
   *
   * @param value allowed object is {@link Covariances }
   */
  public void setCovariances(Covariances value) {
    this.covariances = value;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the name property.
   *
   * @return possible object is {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the size property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getSize() {
    return size;
  }

  /**
   * Sets the value of the size property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setSize(BigInteger value) {
    this.size = value;
  }
}
