//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:18 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.impl.v4_4;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref="{http://www.dmg.org/PMML-4_4}Interval" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;element ref="{http://www.dmg.org/PMML-4_4}Value" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.dmg.org/PMML-4_4}FIELD-NAME" /&gt;
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="optype" use="required" type="{http://www.dmg.org/PMML-4_4}OPTYPE" /&gt;
 *       &lt;attribute name="dataType" use="required" type="{http://www.dmg.org/PMML-4_4}DATATYPE" /&gt;
 *       &lt;attribute name="taxonomy" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="isCyclic" default="0"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="0"/&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"extension", "interval", "value"})
@XmlRootElement(name = "DataField")
public class DataField
    implements org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.DataField {

  @XmlElement(name = "Extension", type = Extension.class)
  protected List<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Extension> extension;

  @XmlElement(name = "Interval", type = Interval.class)
  protected List<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Interval> interval;

  @XmlElement(name = "Value", type = Value.class)
  protected List<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Value> value;

  @XmlAttribute(name = "name", required = true)
  protected String name;

  @XmlAttribute(name = "displayName")
  protected String displayName;

  @XmlAttribute(name = "optype", required = true)
  protected org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.OPTYPE optype;

  @XmlAttribute(name = "dataType", required = true)
  protected org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.DATATYPE dataType;

  @XmlAttribute(name = "taxonomy")
  protected String taxonomy;

  @XmlAttribute(name = "isCyclic")
  protected String isCyclic;

  /**
   * Gets the value of the extension property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extension property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Extension }
   */
  public List<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Extension> getExtension() {
    if (extension == null) {
      extension =
          new ArrayList<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Extension>();
    }
    return this.extension;
  }

  /**
   * Gets the value of the interval property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the interval property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getInterval().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Interval }
   */
  public List<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Interval> getInterval() {
    if (interval == null) {
      interval =
          new ArrayList<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Interval>();
    }
    return this.interval;
  }

  /**
   * Gets the value of the value property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the value property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getValue().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Value }
   */
  public List<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Value> getValue() {
    if (value == null) {
      value = new ArrayList<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Value>();
    }
    return this.value;
  }

  /**
   * Gets the value of the name property.
   *
   * @return possible object is {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the displayName property.
   *
   * @return possible object is {@link String }
   */
  public String getDisplayName() {
    return displayName;
  }

  /**
   * Sets the value of the displayName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDisplayName(String value) {
    this.displayName = value;
  }

  /**
   * Gets the value of the optype property.
   *
   * @return possible object is {@link OPTYPE }
   */
  public org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.OPTYPE getOptype() {
    return optype;
  }

  /**
   * Sets the value of the optype property.
   *
   * @param value allowed object is {@link OPTYPE }
   */
  public void setOptype(org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.OPTYPE value) {
    this.optype = value;
  }

  /**
   * Gets the value of the dataType property.
   *
   * @return possible object is {@link DATATYPE }
   */
  public org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.DATATYPE getDataType() {
    return dataType;
  }

  /**
   * Sets the value of the dataType property.
   *
   * @param value allowed object is {@link DATATYPE }
   */
  public void setDataType(
      org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.DATATYPE value) {
    this.dataType = value;
  }

  /**
   * Gets the value of the taxonomy property.
   *
   * @return possible object is {@link String }
   */
  public String getTaxonomy() {
    return taxonomy;
  }

  /**
   * Sets the value of the taxonomy property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTaxonomy(String value) {
    this.taxonomy = value;
  }

  /**
   * Gets the value of the isCyclic property.
   *
   * @return possible object is {@link String }
   */
  public String getIsCyclic() {
    if (isCyclic == null) {
      return "0";
    } else {
      return isCyclic;
    }
  }

  /**
   * Sets the value of the isCyclic property.
   *
   * @param value allowed object is {@link String }
   */
  public void setIsCyclic(String value) {
    this.isCyclic = value;
  }
}
