//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:18 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.impl.v4_4;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}AR"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}MA"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="constant" type="{http://www.dmg.org/PMML-4_4}REAL-NUMBER" default="0" /&gt;
 *       &lt;attribute name="p" use="required" type="{http://www.dmg.org/PMML-4_4}INT-NUMBER" /&gt;
 *       &lt;attribute name="q" use="required" type="{http://www.dmg.org/PMML-4_4}INT-NUMBER" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"extension", "ar", "ma"})
@XmlRootElement(name = "ARMAPart")
public class ARMAPart {

  @XmlElement(name = "Extension")
  protected List<Extension> extension;

  @XmlElement(name = "AR", required = true)
  protected AR ar;

  @XmlElement(name = "MA", required = true)
  protected MA ma;

  @XmlAttribute(name = "constant")
  protected Double constant;

  @XmlAttribute(name = "p", required = true)
  protected BigInteger p;

  @XmlAttribute(name = "q", required = true)
  protected BigInteger q;

  /**
   * Gets the value of the extension property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extension property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Extension }
   */
  public List<Extension> getExtension() {
    if (extension == null) {
      extension = new ArrayList<Extension>();
    }
    return this.extension;
  }

  /**
   * Gets the value of the ar property.
   *
   * @return possible object is {@link AR }
   */
  public AR getAR() {
    return ar;
  }

  /**
   * Sets the value of the ar property.
   *
   * @param value allowed object is {@link AR }
   */
  public void setAR(AR value) {
    this.ar = value;
  }

  /**
   * Gets the value of the ma property.
   *
   * @return possible object is {@link MA }
   */
  public MA getMA() {
    return ma;
  }

  /**
   * Sets the value of the ma property.
   *
   * @param value allowed object is {@link MA }
   */
  public void setMA(MA value) {
    this.ma = value;
  }

  /**
   * Gets the value of the constant property.
   *
   * @return possible object is {@link Double }
   */
  public double getConstant() {
    if (constant == null) {
      return 0.0D;
    } else {
      return constant;
    }
  }

  /**
   * Sets the value of the constant property.
   *
   * @param value allowed object is {@link Double }
   */
  public void setConstant(Double value) {
    this.constant = value;
  }

  /**
   * Gets the value of the p property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getP() {
    return p;
  }

  /**
   * Sets the value of the p property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setP(BigInteger value) {
    this.p = value;
  }

  /**
   * Gets the value of the q property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getQ() {
    return q;
  }

  /**
   * Sets the value of the q property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setQ(BigInteger value) {
    this.q = value;
  }
}
