<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>mapper-parent</artifactId>
        <groupId>org.treblereel.gwt.xml.mapper</groupId>
        <version>0.11</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>tests-j2cl</artifactId>
    <name>GWT/J2CL XML Mapper - J2CL Tests</name>
    <description>Test cases for J2CL</description>

    <properties>
        <maven.install.skip>true</maven.install.skip>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.treblereel.gwt.xml.mapper</groupId>
            <artifactId>api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.kie.j2cl.tools</groupId>
            <artifactId>junit-annotations</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.kie.j2cl.tools</groupId>
            <artifactId>junit-processor</artifactId>
            <version>v${j2cl.platform.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.kie.j2cl.tools</groupId>
            <artifactId>gwttestcase-emul</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.kie.j2cl.tools</groupId>
            <artifactId>junit-emul</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.version}</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.treblereel.gwt.xml.mapper</groupId>
                            <artifactId>processor</artifactId>
                            <version>${project.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.kie.j2cl.tools</groupId>
                <artifactId>j2cl-maven-plugin</artifactId>
                <version>0.23.8</version>
                <configuration>
                    <compilationLevel>ADVANCED</compilationLevel>
                    <annotationProcessorMode>IGNORE_MAVEN</annotationProcessorMode>
                    <webdriver>chrome</webdriver>
                </configuration>
                <executions>
                    <execution>
                        <id>j2cl-test</id>
                        <goals>
                            <goal>test</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surfire.plugin}</version>
                <configuration>
                    <skipTests>true</skipTests>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
