//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:12 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api;

import java.math.BigInteger;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Neuron" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="numberOfNeurons" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="activationFunction" type="{http://www.dmg.org/PMML-4_4}ACTIVATION-FUNCTION" /&gt;
 *       &lt;attribute name="threshold" type="{http://www.dmg.org/PMML-4_4}REAL-NUMBER" /&gt;
 *       &lt;attribute name="width" type="{http://www.dmg.org/PMML-4_4}REAL-NUMBER" /&gt;
 *       &lt;attribute name="altitude" type="{http://www.dmg.org/PMML-4_4}REAL-NUMBER" /&gt;
 *       &lt;attribute name="normalizationMethod" type="{http://www.dmg.org/PMML-4_4}NN-NORMALIZATION-METHOD" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
public interface NeuralLayer {

  /**
   * Gets the value of the extension property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extension property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Extension }
   */
  List<Extension> getExtension();

  /**
   * Gets the value of the neuron property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the neuron property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getNeuron().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Neuron }
   */
  List<Neuron> getNeuron();

  /**
   * Gets the value of the numberOfNeurons property.
   *
   * @return possible object is {@link BigInteger }
   */
  BigInteger getNumberOfNeurons();

  /**
   * Sets the value of the numberOfNeurons property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  void setNumberOfNeurons(BigInteger value);

  /**
   * Gets the value of the activationFunction property.
   *
   * @return possible object is {@link ACTIVATIONFUNCTION }
   */
  ACTIVATIONFUNCTION getActivationFunction();

  /**
   * Sets the value of the activationFunction property.
   *
   * @param value allowed object is {@link ACTIVATIONFUNCTION }
   */
  void setActivationFunction(ACTIVATIONFUNCTION value);

  /**
   * Gets the value of the threshold property.
   *
   * @return possible object is {@link Double }
   */
  Double getThreshold();

  /**
   * Sets the value of the threshold property.
   *
   * @param value allowed object is {@link Double }
   */
  void setThreshold(Double value);

  /**
   * Gets the value of the width property.
   *
   * @return possible object is {@link Double }
   */
  Double getWidth();

  /**
   * Sets the value of the width property.
   *
   * @param value allowed object is {@link Double }
   */
  void setWidth(Double value);

  /**
   * Gets the value of the altitude property.
   *
   * @return possible object is {@link Double }
   */
  Double getAltitude();

  /**
   * Sets the value of the altitude property.
   *
   * @param value allowed object is {@link Double }
   */
  void setAltitude(Double value);

  /**
   * Gets the value of the normalizationMethod property.
   *
   * @return possible object is {@link NNNORMALIZATIONMETHOD }
   */
  NNNORMALIZATIONMETHOD getNormalizationMethod();

  /**
   * Sets the value of the normalizationMethod property.
   *
   * @param value allowed object is {@link NNNORMALIZATIONMETHOD }
   */
  void setNormalizationMethod(NNNORMALIZATIONMETHOD value);
}
