//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:12 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}FinalNoise"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}FinalPredictedNoise"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}FinalTheta"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}FinalNu"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
public interface ThetaRecursionState {

  /**
   * Gets the value of the finalNoise property.
   *
   * @return possible object is {@link FinalNoise }
   */
  FinalNoise getFinalNoise();

  /**
   * Sets the value of the finalNoise property.
   *
   * @param value allowed object is {@link FinalNoise }
   */
  void setFinalNoise(FinalNoise value);

  /**
   * Gets the value of the finalPredictedNoise property.
   *
   * @return possible object is {@link FinalPredictedNoise }
   */
  FinalPredictedNoise getFinalPredictedNoise();

  /**
   * Sets the value of the finalPredictedNoise property.
   *
   * @param value allowed object is {@link FinalPredictedNoise }
   */
  void setFinalPredictedNoise(FinalPredictedNoise value);

  /**
   * Gets the value of the finalTheta property.
   *
   * @return possible object is {@link FinalTheta }
   */
  FinalTheta getFinalTheta();

  /**
   * Sets the value of the finalTheta property.
   *
   * @param value allowed object is {@link FinalTheta }
   */
  void setFinalTheta(FinalTheta value);

  /**
   * Gets the value of the finalNu property.
   *
   * @return possible object is {@link FinalNu }
   */
  FinalNu getFinalNu();

  /**
   * Sets the value of the finalNu property.
   *
   * @param value allowed object is {@link FinalNu }
   */
  void setFinalNu(FinalNu value);
}
