//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:12 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api;

import java.math.BigInteger;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}AR"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}MA"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="constant" type="{http://www.dmg.org/PMML-4_4}REAL-NUMBER" default="0" /&gt;
 *       &lt;attribute name="p" use="required" type="{http://www.dmg.org/PMML-4_4}INT-NUMBER" /&gt;
 *       &lt;attribute name="q" use="required" type="{http://www.dmg.org/PMML-4_4}INT-NUMBER" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
public interface ARMAPart {

  /**
   * Gets the value of the extension property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extension property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Extension }
   */
  List<Extension> getExtension();

  /**
   * Gets the value of the ar property.
   *
   * @return possible object is {@link AR }
   */
  AR getAR();

  /**
   * Sets the value of the ar property.
   *
   * @param value allowed object is {@link AR }
   */
  void setAR(AR value);

  /**
   * Gets the value of the ma property.
   *
   * @return possible object is {@link MA }
   */
  MA getMA();

  /**
   * Sets the value of the ma property.
   *
   * @param value allowed object is {@link MA }
   */
  void setMA(MA value);

  /**
   * Gets the value of the constant property.
   *
   * @return possible object is {@link Double }
   */
  double getConstant();

  /**
   * Sets the value of the constant property.
   *
   * @param value allowed object is {@link Double }
   */
  void setConstant(Double value);

  /**
   * Gets the value of the p property.
   *
   * @return possible object is {@link BigInteger }
   */
  BigInteger getP();

  /**
   * Sets the value of the p property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  void setP(BigInteger value);

  /**
   * Gets the value of the q property.
   *
   * @return possible object is {@link BigInteger }
   */
  BigInteger getQ();

  /**
   * Sets the value of the q property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  void setQ(BigInteger value);
}
