//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:12 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api;

import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://www.dmg.org/PMML-4_4}euclidean"/&gt;
 *           &lt;element ref="{http://www.dmg.org/PMML-4_4}squaredEuclidean"/&gt;
 *           &lt;element ref="{http://www.dmg.org/PMML-4_4}chebychev"/&gt;
 *           &lt;element ref="{http://www.dmg.org/PMML-4_4}cityBlock"/&gt;
 *           &lt;element ref="{http://www.dmg.org/PMML-4_4}minkowski"/&gt;
 *           &lt;element ref="{http://www.dmg.org/PMML-4_4}simpleMatching"/&gt;
 *           &lt;element ref="{http://www.dmg.org/PMML-4_4}jaccard"/&gt;
 *           &lt;element ref="{http://www.dmg.org/PMML-4_4}tanimoto"/&gt;
 *           &lt;element ref="{http://www.dmg.org/PMML-4_4}binarySimilarity"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="kind" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="distance"/&gt;
 *             &lt;enumeration value="similarity"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="compareFunction" type="{http://www.dmg.org/PMML-4_4}COMPARE-FUNCTION" default="absDiff" /&gt;
 *       &lt;attribute name="minimum" type="{http://www.dmg.org/PMML-4_4}NUMBER" /&gt;
 *       &lt;attribute name="maximum" type="{http://www.dmg.org/PMML-4_4}NUMBER" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
public interface ComparisonMeasure {

  /**
   * Gets the value of the extension property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extension property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Extension }
   */
  List<Extension> getExtension();

  /**
   * Gets the value of the measure property.
   *
   * @return possible object is {@link Euclidean } {@link SquaredEuclidean } {@link Chebychev }
   *     {@link CityBlock } {@link Minkowski } {@link SimpleMatching } {@link Jaccard } {@link
   *     Tanimoto } {@link BinarySimilarity }
   */
  IMeasure getMeasure();

  /**
   * Sets the value of the measure property.
   *
   * @param value allowed object is {@link Euclidean } {@link SquaredEuclidean } {@link Chebychev }
   *     {@link CityBlock } {@link Minkowski } {@link SimpleMatching } {@link Jaccard } {@link
   *     Tanimoto } {@link BinarySimilarity }
   */
  void setMeasure(IMeasure value);

  /**
   * Gets the value of the kind property.
   *
   * @return possible object is {@link String }
   */
  String getKind();

  /**
   * Sets the value of the kind property.
   *
   * @param value allowed object is {@link String }
   */
  void setKind(String value);

  /**
   * Gets the value of the compareFunction property.
   *
   * @return possible object is {@link COMPAREFUNCTION }
   */
  COMPAREFUNCTION getCompareFunction();

  /**
   * Sets the value of the compareFunction property.
   *
   * @param value allowed object is {@link COMPAREFUNCTION }
   */
  void setCompareFunction(COMPAREFUNCTION value);

  /**
   * Gets the value of the minimum property.
   *
   * @return possible object is {@link Double }
   */
  Double getMinimum();

  /**
   * Sets the value of the minimum property.
   *
   * @param value allowed object is {@link Double }
   */
  void setMinimum(Double value);

  /**
   * Gets the value of the maximum property.
   *
   * @return possible object is {@link Double }
   */
  Double getMaximum();

  /**
   * Sets the value of the maximum property.
   *
   * @param value allowed object is {@link Double }
   */
  void setMaximum(Double value);
}
