//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:12 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api;

import java.math.BigInteger;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}VerificationFields"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}InlineTable"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="recordCount" type="{http://www.dmg.org/PMML-4_4}INT-NUMBER" /&gt;
 *       &lt;attribute name="fieldCount" type="{http://www.dmg.org/PMML-4_4}INT-NUMBER" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
public interface ModelVerification {

  /**
   * Gets the value of the extension property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extension property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Extension }
   */
  List<Extension> getExtension();

  /**
   * Gets the value of the verificationFields property.
   *
   * @return possible object is {@link VerificationFields }
   */
  VerificationFields getVerificationFields();

  /**
   * Sets the value of the verificationFields property.
   *
   * @param value allowed object is {@link VerificationFields }
   */
  void setVerificationFields(VerificationFields value);

  /**
   * Gets the value of the inlineTable property.
   *
   * @return possible object is {@link InlineTable }
   */
  InlineTable getInlineTable();

  /**
   * Sets the value of the inlineTable property.
   *
   * @param value allowed object is {@link InlineTable }
   */
  void setInlineTable(InlineTable value);

  /**
   * Gets the value of the recordCount property.
   *
   * @return possible object is {@link BigInteger }
   */
  BigInteger getRecordCount();

  /**
   * Sets the value of the recordCount property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  void setRecordCount(BigInteger value);

  /**
   * Gets the value of the fieldCount property.
   *
   * @return possible object is {@link BigInteger }
   */
  BigInteger getFieldCount();

  /**
   * Sets the value of the fieldCount property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  void setFieldCount(BigInteger value);
}
