//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:12 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api;

import java.math.BigInteger;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}MiningSchema"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}ModelStats" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}LocalTransformations" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Constraints" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Item" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Itemset" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}SetPredicate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Sequence" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}SequenceRule" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="modelName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="functionName" use="required" type="{http://www.dmg.org/PMML-4_4}MINING-FUNCTION" /&gt;
 *       &lt;attribute name="algorithmName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="numberOfTransactions" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="maxNumberOfItemsPerTransaction" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="avgNumberOfItemsPerTransaction" type="{http://www.dmg.org/PMML-4_4}REAL-NUMBER" /&gt;
 *       &lt;attribute name="numberOfTransactionGroups" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="maxNumberOfTAsPerTAGroup" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="avgNumberOfTAsPerTAGroup" type="{http://www.dmg.org/PMML-4_4}REAL-NUMBER" /&gt;
 *       &lt;attribute name="isScorable" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
public interface SequenceModel {

  /**
   * Gets the value of the extension property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extension property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Extension }
   */
  List<Extension> getExtension();

  /**
   * Gets the value of the miningSchema property.
   *
   * @return possible object is {@link MiningSchema }
   */
  MiningSchema getMiningSchema();

  /**
   * Sets the value of the miningSchema property.
   *
   * @param value allowed object is {@link MiningSchema }
   */
  void setMiningSchema(MiningSchema value);

  /**
   * Gets the value of the modelStats property.
   *
   * @return possible object is {@link ModelStats }
   */
  ModelStats getModelStats();

  /**
   * Sets the value of the modelStats property.
   *
   * @param value allowed object is {@link ModelStats }
   */
  void setModelStats(ModelStats value);

  /**
   * Gets the value of the localTransformations property.
   *
   * @return possible object is {@link LocalTransformations }
   */
  LocalTransformations getLocalTransformations();

  /**
   * Sets the value of the localTransformations property.
   *
   * @param value allowed object is {@link LocalTransformations }
   */
  void setLocalTransformations(LocalTransformations value);

  /**
   * Gets the value of the constraints property.
   *
   * @return possible object is {@link Constraints }
   */
  Constraints getConstraints();

  /**
   * Sets the value of the constraints property.
   *
   * @param value allowed object is {@link Constraints }
   */
  void setConstraints(Constraints value);

  /**
   * Gets the value of the item property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the item property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getItem().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Item }
   */
  List<Item> getItem();

  /**
   * Gets the value of the itemset property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the itemset property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getItemset().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Itemset }
   */
  List<Itemset> getItemset();

  /**
   * Gets the value of the setPredicate property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the setPredicate property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getSetPredicate().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link SetPredicate }
   */
  List<SetPredicate> getSetPredicate();

  /**
   * Gets the value of the sequence property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the sequence property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getSequence().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Sequence }
   */
  List<Sequence> getSequence();

  /**
   * Gets the value of the sequenceRule property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the sequenceRule property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getSequenceRule().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link SequenceRule }
   */
  List<SequenceRule> getSequenceRule();

  /**
   * Gets the value of the modelName property.
   *
   * @return possible object is {@link String }
   */
  String getModelName();

  /**
   * Sets the value of the modelName property.
   *
   * @param value allowed object is {@link String }
   */
  void setModelName(String value);

  /**
   * Gets the value of the functionName property.
   *
   * @return possible object is {@link MININGFUNCTION }
   */
  MININGFUNCTION getFunctionName();

  /**
   * Sets the value of the functionName property.
   *
   * @param value allowed object is {@link MININGFUNCTION }
   */
  void setFunctionName(MININGFUNCTION value);

  /**
   * Gets the value of the algorithmName property.
   *
   * @return possible object is {@link String }
   */
  String getAlgorithmName();

  /**
   * Sets the value of the algorithmName property.
   *
   * @param value allowed object is {@link String }
   */
  void setAlgorithmName(String value);

  /**
   * Gets the value of the numberOfTransactions property.
   *
   * @return possible object is {@link BigInteger }
   */
  BigInteger getNumberOfTransactions();

  /**
   * Sets the value of the numberOfTransactions property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  void setNumberOfTransactions(BigInteger value);

  /**
   * Gets the value of the maxNumberOfItemsPerTransaction property.
   *
   * @return possible object is {@link BigInteger }
   */
  BigInteger getMaxNumberOfItemsPerTransaction();

  /**
   * Sets the value of the maxNumberOfItemsPerTransaction property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  void setMaxNumberOfItemsPerTransaction(BigInteger value);

  /**
   * Gets the value of the avgNumberOfItemsPerTransaction property.
   *
   * @return possible object is {@link Double }
   */
  Double getAvgNumberOfItemsPerTransaction();

  /**
   * Sets the value of the avgNumberOfItemsPerTransaction property.
   *
   * @param value allowed object is {@link Double }
   */
  void setAvgNumberOfItemsPerTransaction(Double value);

  /**
   * Gets the value of the numberOfTransactionGroups property.
   *
   * @return possible object is {@link BigInteger }
   */
  BigInteger getNumberOfTransactionGroups();

  /**
   * Sets the value of the numberOfTransactionGroups property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  void setNumberOfTransactionGroups(BigInteger value);

  /**
   * Gets the value of the maxNumberOfTAsPerTAGroup property.
   *
   * @return possible object is {@link BigInteger }
   */
  BigInteger getMaxNumberOfTAsPerTAGroup();

  /**
   * Sets the value of the maxNumberOfTAsPerTAGroup property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  void setMaxNumberOfTAsPerTAGroup(BigInteger value);

  /**
   * Gets the value of the avgNumberOfTAsPerTAGroup property.
   *
   * @return possible object is {@link Double }
   */
  Double getAvgNumberOfTAsPerTAGroup();

  /**
   * Sets the value of the avgNumberOfTAsPerTAGroup property.
   *
   * @param value allowed object is {@link Double }
   */
  void setAvgNumberOfTAsPerTAGroup(Double value);

  /**
   * Gets the value of the isScorable property.
   *
   * @return possible object is {@link Boolean }
   */
  boolean isIsScorable();

  /**
   * Sets the value of the isScorable property.
   *
   * @param value allowed object is {@link Boolean }
   */
  void setIsScorable(Boolean value);
}
