//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:12 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api;

import java.math.BigInteger;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}TimeCycle" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}TimeException" maxOccurs="2" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" type="{http://www.dmg.org/PMML-4_4}TIME-ANCHOR-TYPE" /&gt;
 *       &lt;attribute name="offset" type="{http://www.dmg.org/PMML-4_4}INT-NUMBER" /&gt;
 *       &lt;attribute name="stepsize" type="{http://www.dmg.org/PMML-4_4}INT-NUMBER" /&gt;
 *       &lt;attribute name="displayName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
public interface TimeAnchor {

  /**
   * Gets the value of the timeCycle property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the timeCycle property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getTimeCycle().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link TimeCycle }
   */
  List<TimeCycle> getTimeCycle();

  /**
   * Gets the value of the timeException property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the timeException property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getTimeException().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link TimeException }
   */
  List<TimeException> getTimeException();

  /**
   * Gets the value of the type property.
   *
   * @return possible object is {@link TIMEANCHORTYPE }
   */
  TIMEANCHORTYPE getType();

  /**
   * Sets the value of the type property.
   *
   * @param value allowed object is {@link TIMEANCHORTYPE }
   */
  void setType(TIMEANCHORTYPE value);

  /**
   * Gets the value of the offset property.
   *
   * @return possible object is {@link BigInteger }
   */
  BigInteger getOffset();

  /**
   * Sets the value of the offset property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  void setOffset(BigInteger value);

  /**
   * Gets the value of the stepsize property.
   *
   * @return possible object is {@link BigInteger }
   */
  BigInteger getStepsize();

  /**
   * Sets the value of the stepsize property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  void setStepsize(BigInteger value);

  /**
   * Gets the value of the displayName property.
   *
   * @return possible object is {@link String }
   */
  String getDisplayName();

  /**
   * Sets the value of the displayName property.
   *
   * @param value allowed object is {@link String }
   */
  void setDisplayName(String value);
}
