<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>mapper-parent</artifactId>
        <groupId>org.treblereel.gwt.xml.mapper</groupId>
        <version>0.11</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>tests-gwt2</artifactId>
    <packaging>gwt-lib</packaging>
    <name>GWT/J2CL XML Mapper - GWT2 Tests</name>
    <description>Test cases for GWT2</description>

    <properties>
        <gwt.version>2.12.2</gwt.version>
        <maven.gwt.plugin>1.3.0</maven.gwt.plugin>
        <maven.install.skip>true</maven.install.skip>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.treblereel.gwt.xml.mapper</groupId>
            <artifactId>api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.gwtproject</groupId>
            <artifactId>gwt-user</artifactId>
            <version>${gwt.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.gwtproject</groupId>
            <artifactId>gwt-dev</artifactId>
            <version>${gwt.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.version}</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.treblereel.gwt.xml.mapper</groupId>
                            <artifactId>processor</artifactId>
                            <version>${project.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.ltgt.gwt.maven</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>${maven.gwt.plugin}</version>
                <extensions>true</extensions>
                <configuration>
                    <generateInheritsFromDependencies>false</generateInheritsFromDependencies>
                    <moduleName>org.treblereel.gwt.xml.mapper.MapperTest</moduleName>
                    <includes>**/*Suite.java</includes>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <version>2.4.1</version>
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>${basedir}</directory>
                            <includes>
                                <include>war/</include>
                                <include>gwt-unitCache/</include>
                                <include>src/main/webapp/WEB-INF/deploy/</include>
                                <include>src/main/webapp/WEB-INF/classes/</include>
                                <include>src/main/webapp/WEB-INF/lib/*</include>
                                <include>src/main/webapp/WEB-INF/lib/**/*</include>
                                <include>target/war</include>
                            </includes>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
