//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:18 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.impl.v4_4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.IDistribution;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;group ref="{http://www.dmg.org/PMML-4_4}CONTINUOUS-DISTRIBUTION-TYPES"/&gt;
 *         &lt;group ref="{http://www.dmg.org/PMML-4_4}DISCRETE-DISTRIBUTION-TYPES"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"distribution"})
@XmlRootElement(name = "Baseline")
public class Baseline {

  @XmlElementRefs({
    @XmlElementRef(
        name = "AnyDistribution",
        namespace = "http://www.dmg.org/PMML-4_4",
        type = AnyDistribution.class,
        required = false),
    @XmlElementRef(
        name = "GaussianDistribution",
        namespace = "http://www.dmg.org/PMML-4_4",
        type = GaussianDistribution.class,
        required = false),
    @XmlElementRef(
        name = "PoissonDistribution",
        namespace = "http://www.dmg.org/PMML-4_4",
        type = PoissonDistribution.class,
        required = false),
    @XmlElementRef(
        name = "UniformDistribution",
        namespace = "http://www.dmg.org/PMML-4_4",
        type = UniformDistribution.class,
        required = false),
    @XmlElementRef(
        name = "CountTable",
        namespace = "http://www.dmg.org/PMML-4_4",
        type = CountTable.class,
        required = false),
    @XmlElementRef(
        name = "NormalizedCountTable",
        namespace = "http://www.dmg.org/PMML-4_4",
        type = NormalizedCountTable.class,
        required = false),
    @XmlElementRef(
        name = "FieldRef",
        namespace = "http://www.dmg.org/PMML-4_4",
        type = FieldRef.class,
        required = false)
  })
  protected List<IDistribution> distribution;

  /**
   * Gets the value of the distribution property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the distribution property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getDistribution().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link AnyDistribution } {@link
   * GaussianDistribution } {@link PoissonDistribution } {@link UniformDistribution } {@link
   * CountTable } {@link NormalizedCountTable } {@link FieldRef }
   */
  public List<IDistribution> getDistribution() {
    if (distribution == null) {
      distribution = new ArrayList<IDistribution>();
    }
    return this.distribution;
  }
}
