//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:18 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.impl.v4_4;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Level"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Trend_ExpoSmooth" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Seasonality_ExpoSmooth" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}TimeValue" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="RMSE" type="{http://www.dmg.org/PMML-4_4}REAL-NUMBER" /&gt;
 *       &lt;attribute name="transformation" default="none"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="none"/&gt;
 *             &lt;enumeration value="logarithmic"/&gt;
 *             &lt;enumeration value="squareroot"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"level", "trendExpoSmooth", "seasonalityExpoSmooth", "timeValue"})
@XmlRootElement(name = "ExponentialSmoothing")
public class ExponentialSmoothing {

  @XmlElement(name = "Level", required = true)
  protected Level level;

  @XmlElement(name = "Trend_ExpoSmooth")
  protected TrendExpoSmooth trendExpoSmooth;

  @XmlElement(name = "Seasonality_ExpoSmooth")
  protected SeasonalityExpoSmooth seasonalityExpoSmooth;

  @XmlElement(name = "TimeValue")
  protected List<TimeValue> timeValue;

  @XmlAttribute(name = "RMSE")
  protected Double rmse;

  @XmlAttribute(name = "transformation")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String transformation;

  /**
   * Gets the value of the level property.
   *
   * @return possible object is {@link Level }
   */
  public Level getLevel() {
    return level;
  }

  /**
   * Sets the value of the level property.
   *
   * @param value allowed object is {@link Level }
   */
  public void setLevel(Level value) {
    this.level = value;
  }

  /**
   * Gets the value of the trendExpoSmooth property.
   *
   * @return possible object is {@link TrendExpoSmooth }
   */
  public TrendExpoSmooth getTrendExpoSmooth() {
    return trendExpoSmooth;
  }

  /**
   * Sets the value of the trendExpoSmooth property.
   *
   * @param value allowed object is {@link TrendExpoSmooth }
   */
  public void setTrendExpoSmooth(TrendExpoSmooth value) {
    this.trendExpoSmooth = value;
  }

  /**
   * Gets the value of the seasonalityExpoSmooth property.
   *
   * @return possible object is {@link SeasonalityExpoSmooth }
   */
  public SeasonalityExpoSmooth getSeasonalityExpoSmooth() {
    return seasonalityExpoSmooth;
  }

  /**
   * Sets the value of the seasonalityExpoSmooth property.
   *
   * @param value allowed object is {@link SeasonalityExpoSmooth }
   */
  public void setSeasonalityExpoSmooth(SeasonalityExpoSmooth value) {
    this.seasonalityExpoSmooth = value;
  }

  /**
   * Gets the value of the timeValue property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the timeValue property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getTimeValue().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link TimeValue }
   */
  public List<TimeValue> getTimeValue() {
    if (timeValue == null) {
      timeValue = new ArrayList<TimeValue>();
    }
    return this.timeValue;
  }

  /**
   * Gets the value of the rmse property.
   *
   * @return possible object is {@link Double }
   */
  public Double getRMSE() {
    return rmse;
  }

  /**
   * Sets the value of the rmse property.
   *
   * @param value allowed object is {@link Double }
   */
  public void setRMSE(Double value) {
    this.rmse = value;
  }

  /**
   * Gets the value of the transformation property.
   *
   * @return possible object is {@link String }
   */
  public String getTransformation() {
    if (transformation == null) {
      return "none";
    } else {
      return transformation;
    }
  }

  /**
   * Sets the value of the transformation property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTransformation(String value) {
    this.transformation = value;
  }
}
