//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:18 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.impl.v4_4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.IExpression;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}LinearNorm" maxOccurs="unbounded" minOccurs="2"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="mapMissingTo" type="{http://www.dmg.org/PMML-4_4}NUMBER" /&gt;
 *       &lt;attribute name="field" use="required" type="{http://www.dmg.org/PMML-4_4}FIELD-NAME" /&gt;
 *       &lt;attribute name="outliers" type="{http://www.dmg.org/PMML-4_4}OUTLIER-TREATMENT-METHOD" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"extension", "linearNorm"})
@XmlRootElement(name = "NormContinuous")
public class NormContinuous
    implements IExpression,
        org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.NormContinuous {

  @XmlElement(name = "Extension", type = Extension.class)
  protected List<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Extension> extension;

  @XmlElement(name = "LinearNorm", required = true, type = LinearNorm.class)
  protected List<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.LinearNorm> linearNorm;

  @XmlAttribute(name = "mapMissingTo")
  protected Double mapMissingTo;

  @XmlAttribute(name = "field", required = true)
  protected String field;

  @XmlAttribute(name = "outliers")
  protected org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.OUTLIERTREATMENTMETHOD
      outliers;

  /**
   * Gets the value of the extension property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extension property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Extension }
   */
  public List<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Extension> getExtension() {
    if (extension == null) {
      extension =
          new ArrayList<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Extension>();
    }
    return this.extension;
  }

  /**
   * Gets the value of the linearNorm property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the linearNorm property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getLinearNorm().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link LinearNorm }
   */
  public List<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.LinearNorm>
      getLinearNorm() {
    if (linearNorm == null) {
      linearNorm =
          new ArrayList<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.LinearNorm>();
    }
    return this.linearNorm;
  }

  /**
   * Gets the value of the mapMissingTo property.
   *
   * @return possible object is {@link Double }
   */
  public Double getMapMissingTo() {
    return mapMissingTo;
  }

  /**
   * Sets the value of the mapMissingTo property.
   *
   * @param value allowed object is {@link Double }
   */
  public void setMapMissingTo(Double value) {
    this.mapMissingTo = value;
  }

  /**
   * Gets the value of the field property.
   *
   * @return possible object is {@link String }
   */
  public String getField() {
    return field;
  }

  /**
   * Sets the value of the field property.
   *
   * @param value allowed object is {@link String }
   */
  public void setField(String value) {
    this.field = value;
  }

  /**
   * Gets the value of the outliers property.
   *
   * @return possible object is {@link OUTLIERTREATMENTMETHOD }
   */
  public org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.OUTLIERTREATMENTMETHOD
      getOutliers() {
    return outliers;
  }

  /**
   * Sets the value of the outliers property.
   *
   * @param value allowed object is {@link OUTLIERTREATMENTMETHOD }
   */
  public void setOutliers(
      org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.OUTLIERTREATMENTMETHOD value) {
    this.outliers = value;
  }
}
