//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:18 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.impl.v4_4;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.IMatrix;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Array"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"array"})
@XmlRootElement(name = "NUM-ARRAY")
public class NUMARRAY
    implements IMatrix, org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.NUMARRAY {

  @XmlElement(name = "Array", type = ArrayType.class)
  protected org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.ArrayType array;

  /**
   * Gets the value of the array property.
   *
   * @return possible object is {@link ArrayType }
   */
  public org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.ArrayType getArray() {
    return array;
  }

  /**
   * Sets the value of the array property.
   *
   * @param value allowed object is {@link ArrayType }
   */
  public void setArray(org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.ArrayType value) {
    this.array = value;
  }
}
