//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:18 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.impl.v4_4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Partition" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="displayValue" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="priorProbability" type="{http://www.dmg.org/PMML-4_4}PROB-NUMBER" /&gt;
 *       &lt;attribute name="defaultValue" type="{http://www.dmg.org/PMML-4_4}NUMBER" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"extension", "partition"})
@XmlRootElement(name = "TargetValue")
public class TargetValue
    implements org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.TargetValue {

  @XmlElement(name = "Extension", type = Extension.class)
  protected List<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Extension> extension;

  @XmlElement(name = "Partition", type = Partition.class)
  protected org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Partition partition;

  @XmlAttribute(name = "value")
  protected String value;

  @XmlAttribute(name = "displayValue")
  protected String displayValue;

  @XmlAttribute(name = "priorProbability")
  protected Double priorProbability;

  @XmlAttribute(name = "defaultValue")
  protected Double defaultValue;

  /**
   * Gets the value of the extension property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extension property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Extension }
   */
  public List<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Extension> getExtension() {
    if (extension == null) {
      extension =
          new ArrayList<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Extension>();
    }
    return this.extension;
  }

  /**
   * Gets the value of the partition property.
   *
   * @return possible object is {@link Partition }
   */
  public org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Partition getPartition() {
    return partition;
  }

  /**
   * Sets the value of the partition property.
   *
   * @param value allowed object is {@link Partition }
   */
  public void setPartition(
      org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Partition value) {
    this.partition = value;
  }

  /**
   * Gets the value of the value property.
   *
   * @return possible object is {@link String }
   */
  public String getValue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   *
   * @param value allowed object is {@link String }
   */
  public void setValue(String value) {
    this.value = value;
  }

  /**
   * Gets the value of the displayValue property.
   *
   * @return possible object is {@link String }
   */
  public String getDisplayValue() {
    return displayValue;
  }

  /**
   * Sets the value of the displayValue property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDisplayValue(String value) {
    this.displayValue = value;
  }

  /**
   * Gets the value of the priorProbability property.
   *
   * @return possible object is {@link Double }
   */
  public Double getPriorProbability() {
    return priorProbability;
  }

  /**
   * Sets the value of the priorProbability property.
   *
   * @param value allowed object is {@link Double }
   */
  public void setPriorProbability(Double value) {
    this.priorProbability = value;
  }

  /**
   * Gets the value of the defaultValue property.
   *
   * @return possible object is {@link Double }
   */
  public Double getDefaultValue() {
    return defaultValue;
  }

  /**
   * Sets the value of the defaultValue property.
   *
   * @param value allowed object is {@link Double }
   */
  public void setDefaultValue(Double value) {
    this.defaultValue = value;
  }
}
