//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:18 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.impl.v4_4;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}INT-ARRAY"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" type="{http://www.dmg.org/PMML-4_4}TIME-EXCEPTION-TYPE" /&gt;
 *       &lt;attribute name="count" type="{http://www.dmg.org/PMML-4_4}INT-NUMBER" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"intarray"})
@XmlRootElement(name = "TimeException")
public class TimeException {

  @XmlElement(name = "INT-ARRAY", required = true)
  protected INTARRAY intarray;

  @XmlAttribute(name = "type")
  protected TIMEEXCEPTIONTYPE type;

  @XmlAttribute(name = "count")
  protected BigInteger count;

  /**
   * Gets the value of the intarray property.
   *
   * @return possible object is {@link INTARRAY }
   */
  public INTARRAY getINTARRAY() {
    return intarray;
  }

  /**
   * Sets the value of the intarray property.
   *
   * @param value allowed object is {@link INTARRAY }
   */
  public void setINTARRAY(INTARRAY value) {
    this.intarray = value;
  }

  /**
   * Gets the value of the type property.
   *
   * @return possible object is {@link TIMEEXCEPTIONTYPE }
   */
  public TIMEEXCEPTIONTYPE getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   *
   * @param value allowed object is {@link TIMEEXCEPTIONTYPE }
   */
  public void setType(TIMEEXCEPTIONTYPE value) {
    this.type = value;
  }

  /**
   * Gets the value of the count property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getCount() {
    return count;
  }

  /**
   * Sets the value of the count property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setCount(BigInteger value) {
    this.count = value;
  }
}
