//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:18 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.impl.v4_4;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Counts" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}NumericInfo" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}DiscrStats" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}ContStats" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Anova" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="field" type="{http://www.dmg.org/PMML-4_4}FIELD-NAME" /&gt;
 *       &lt;attribute name="weighted" default="0"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="0"/&gt;
 *             &lt;enumeration value="1"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"extension", "counts", "numericInfo", "discrStats", "contStats", "anova"})
@XmlRootElement(name = "UnivariateStats")
public class UnivariateStats
    implements org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.UnivariateStats {

  @XmlElement(name = "Extension", type = Extension.class)
  protected List<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Extension> extension;

  @XmlElement(name = "Counts", type = Counts.class)
  protected org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Counts counts;

  @XmlElement(name = "NumericInfo", type = NumericInfo.class)
  protected org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.NumericInfo numericInfo;

  @XmlElement(name = "DiscrStats", type = DiscrStats.class)
  protected org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.DiscrStats discrStats;

  @XmlElement(name = "ContStats", type = ContStats.class)
  protected org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.ContStats contStats;

  @XmlElement(name = "Anova", type = Anova.class)
  protected org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Anova anova;

  @XmlAttribute(name = "field")
  protected String field;

  @XmlAttribute(name = "weighted")
  protected String weighted;

  /**
   * Gets the value of the extension property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extension property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Extension }
   */
  public List<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Extension> getExtension() {
    if (extension == null) {
      extension =
          new ArrayList<org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Extension>();
    }
    return this.extension;
  }

  /**
   * Gets the value of the counts property.
   *
   * @return possible object is {@link Counts }
   */
  public org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Counts getCounts() {
    return counts;
  }

  /**
   * Sets the value of the counts property.
   *
   * @param value allowed object is {@link Counts }
   */
  public void setCounts(org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Counts value) {
    this.counts = value;
  }

  /**
   * Gets the value of the numericInfo property.
   *
   * @return possible object is {@link NumericInfo }
   */
  public org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.NumericInfo getNumericInfo() {
    return numericInfo;
  }

  /**
   * Sets the value of the numericInfo property.
   *
   * @param value allowed object is {@link NumericInfo }
   */
  public void setNumericInfo(
      org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.NumericInfo value) {
    this.numericInfo = value;
  }

  /**
   * Gets the value of the discrStats property.
   *
   * @return possible object is {@link DiscrStats }
   */
  public org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.DiscrStats getDiscrStats() {
    return discrStats;
  }

  /**
   * Sets the value of the discrStats property.
   *
   * @param value allowed object is {@link DiscrStats }
   */
  public void setDiscrStats(
      org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.DiscrStats value) {
    this.discrStats = value;
  }

  /**
   * Gets the value of the contStats property.
   *
   * @return possible object is {@link ContStats }
   */
  public org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.ContStats getContStats() {
    return contStats;
  }

  /**
   * Sets the value of the contStats property.
   *
   * @param value allowed object is {@link ContStats }
   */
  public void setContStats(
      org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.ContStats value) {
    this.contStats = value;
  }

  /**
   * Gets the value of the anova property.
   *
   * @return possible object is {@link Anova }
   */
  public org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Anova getAnova() {
    return anova;
  }

  /**
   * Sets the value of the anova property.
   *
   * @param value allowed object is {@link Anova }
   */
  public void setAnova(org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api.Anova value) {
    this.anova = value;
  }

  /**
   * Gets the value of the field property.
   *
   * @return possible object is {@link String }
   */
  public String getField() {
    return field;
  }

  /**
   * Sets the value of the field property.
   *
   * @param value allowed object is {@link String }
   */
  public void setField(String value) {
    this.field = value;
  }

  /**
   * Gets the value of the weighted property.
   *
   * @return possible object is {@link String }
   */
  public String getWeighted() {
    if (weighted == null) {
      return "0";
    } else {
      return weighted;
    }
  }

  /**
   * Sets the value of the weighted property.
   *
   * @param value allowed object is {@link String }
   */
  public void setWeighted(String value) {
    this.weighted = value;
  }
}
