//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:12 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api;

import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="field" type="{http://www.dmg.org/PMML-4_4}FIELD-NAME" /&gt;
 *       &lt;attribute name="category" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="mappedValue" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="weight" type="{http://www.dmg.org/PMML-4_4}REAL-NUMBER" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
public interface Item {

  /**
   * Gets the value of the extension property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extension property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Extension }
   */
  List<Extension> getExtension();

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  String getId();

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  void setId(String value);

  /**
   * Gets the value of the value property.
   *
   * @return possible object is {@link String }
   */
  String getValue();

  /**
   * Sets the value of the value property.
   *
   * @param value allowed object is {@link String }
   */
  void setValue(String value);

  /**
   * Gets the value of the field property.
   *
   * @return possible object is {@link String }
   */
  String getField();

  /**
   * Sets the value of the field property.
   *
   * @param value allowed object is {@link String }
   */
  void setField(String value);

  /**
   * Gets the value of the category property.
   *
   * @return possible object is {@link String }
   */
  String getCategory();

  /**
   * Sets the value of the category property.
   *
   * @param value allowed object is {@link String }
   */
  void setCategory(String value);

  /**
   * Gets the value of the mappedValue property.
   *
   * @return possible object is {@link String }
   */
  String getMappedValue();

  /**
   * Sets the value of the mappedValue property.
   *
   * @param value allowed object is {@link String }
   */
  void setMappedValue(String value);

  /**
   * Gets the value of the weight property.
   *
   * @return possible object is {@link Double }
   */
  Double getWeight();

  /**
   * Sets the value of the weight property.
   *
   * @param value allowed object is {@link Double }
   */
  void setWeight(Double value);
}
