//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:12 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api;

import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.dmg.org/PMML-4_4}FIELD-NAME" /&gt;
 *       &lt;attribute name="usageType" type="{http://www.dmg.org/PMML-4_4}FIELD-USAGE-TYPE" /&gt;
 *       &lt;attribute name="optype" type="{http://www.dmg.org/PMML-4_4}OPTYPE" /&gt;
 *       &lt;attribute name="importance" type="{http://www.dmg.org/PMML-4_4}PROB-NUMBER" /&gt;
 *       &lt;attribute name="outliers" type="{http://www.dmg.org/PMML-4_4}OUTLIER-TREATMENT-METHOD" /&gt;
 *       &lt;attribute name="lowValue" type="{http://www.dmg.org/PMML-4_4}NUMBER" /&gt;
 *       &lt;attribute name="highValue" type="{http://www.dmg.org/PMML-4_4}NUMBER" /&gt;
 *       &lt;attribute name="missingValueReplacement" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="missingValueTreatment" type="{http://www.dmg.org/PMML-4_4}MISSING-VALUE-TREATMENT-METHOD" /&gt;
 *       &lt;attribute name="invalidValueTreatment" type="{http://www.dmg.org/PMML-4_4}INVALID-VALUE-TREATMENT-METHOD" /&gt;
 *       &lt;attribute name="invalidValueReplacement" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
public interface MiningField {

  /**
   * Gets the value of the extension property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extension property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Extension }
   */
  List<Extension> getExtension();

  /**
   * Gets the value of the name property.
   *
   * @return possible object is {@link String }
   */
  String getName();

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  void setName(String value);

  /**
   * Gets the value of the usageType property.
   *
   * @return possible object is {@link FIELDUSAGETYPE }
   */
  FIELDUSAGETYPE getUsageType();

  /**
   * Sets the value of the usageType property.
   *
   * @param value allowed object is {@link FIELDUSAGETYPE }
   */
  void setUsageType(FIELDUSAGETYPE value);

  /**
   * Gets the value of the optype property.
   *
   * @return possible object is {@link OPTYPE }
   */
  OPTYPE getOptype();

  /**
   * Sets the value of the optype property.
   *
   * @param value allowed object is {@link OPTYPE }
   */
  void setOptype(OPTYPE value);

  /**
   * Gets the value of the importance property.
   *
   * @return possible object is {@link Double }
   */
  Double getImportance();

  /**
   * Sets the value of the importance property.
   *
   * @param value allowed object is {@link Double }
   */
  void setImportance(Double value);

  /**
   * Gets the value of the outliers property.
   *
   * @return possible object is {@link OUTLIERTREATMENTMETHOD }
   */
  OUTLIERTREATMENTMETHOD getOutliers();

  /**
   * Sets the value of the outliers property.
   *
   * @param value allowed object is {@link OUTLIERTREATMENTMETHOD }
   */
  void setOutliers(OUTLIERTREATMENTMETHOD value);

  /**
   * Gets the value of the lowValue property.
   *
   * @return possible object is {@link Double }
   */
  Double getLowValue();

  /**
   * Sets the value of the lowValue property.
   *
   * @param value allowed object is {@link Double }
   */
  void setLowValue(Double value);

  /**
   * Gets the value of the highValue property.
   *
   * @return possible object is {@link Double }
   */
  Double getHighValue();

  /**
   * Sets the value of the highValue property.
   *
   * @param value allowed object is {@link Double }
   */
  void setHighValue(Double value);

  /**
   * Gets the value of the missingValueReplacement property.
   *
   * @return possible object is {@link String }
   */
  String getMissingValueReplacement();

  /**
   * Sets the value of the missingValueReplacement property.
   *
   * @param value allowed object is {@link String }
   */
  void setMissingValueReplacement(String value);

  /**
   * Gets the value of the missingValueTreatment property.
   *
   * @return possible object is {@link MISSINGVALUETREATMENTMETHOD }
   */
  MISSINGVALUETREATMENTMETHOD getMissingValueTreatment();

  /**
   * Sets the value of the missingValueTreatment property.
   *
   * @param value allowed object is {@link MISSINGVALUETREATMENTMETHOD }
   */
  void setMissingValueTreatment(MISSINGVALUETREATMENTMETHOD value);

  /**
   * Gets the value of the invalidValueTreatment property.
   *
   * @return possible object is {@link INVALIDVALUETREATMENTMETHOD }
   */
  INVALIDVALUETREATMENTMETHOD getInvalidValueTreatment();

  /**
   * Sets the value of the invalidValueTreatment property.
   *
   * @param value allowed object is {@link INVALIDVALUETREATMENTMETHOD }
   */
  void setInvalidValueTreatment(INVALIDVALUETREATMENTMETHOD value);

  /**
   * Gets the value of the invalidValueReplacement property.
   *
   * @return possible object is {@link String }
   */
  String getInvalidValueReplacement();

  /**
   * Sets the value of the invalidValueReplacement property.
   *
   * @param value allowed object is {@link String }
   */
  void setInvalidValueReplacement(String value);
}
