//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:12 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api;

import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Header"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}MiningBuildTask" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}DataDictionary"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}TransformationDictionary" minOccurs="0"/&gt;
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;group ref="{http://www.dmg.org/PMML-4_4}MODEL-ELEMENT"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
public interface PMML {

  /**
   * Gets the value of the header property.
   *
   * @return possible object is {@link Header }
   */
  Header getHeader();

  /**
   * Sets the value of the header property.
   *
   * @param value allowed object is {@link Header }
   */
  void setHeader(Header value);

  /**
   * Gets the value of the miningBuildTask property.
   *
   * @return possible object is {@link MiningBuildTask }
   */
  MiningBuildTask getMiningBuildTask();

  /**
   * Sets the value of the miningBuildTask property.
   *
   * @param value allowed object is {@link MiningBuildTask }
   */
  void setMiningBuildTask(MiningBuildTask value);

  /**
   * Gets the value of the dataDictionary property.
   *
   * @return possible object is {@link DataDictionary }
   */
  DataDictionary getDataDictionary();

  /**
   * Sets the value of the dataDictionary property.
   *
   * @param value allowed object is {@link DataDictionary }
   */
  void setDataDictionary(DataDictionary value);

  /**
   * Gets the value of the transformationDictionary property.
   *
   * @return possible object is {@link TransformationDictionary }
   */
  TransformationDictionary getTransformationDictionary();

  /**
   * Sets the value of the transformationDictionary property.
   *
   * @param value allowed object is {@link TransformationDictionary }
   */
  void setTransformationDictionary(TransformationDictionary value);

  /**
   * Gets the value of the model property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the model property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getModel().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link AnomalyDetectionModel }
   * {@link AssociationModel } {@link BayesianNetworkModel } {@link BaselineModel } {@link
   * ClusteringModel } {@link GaussianProcessModel } {@link GeneralRegressionModel } {@link
   * MiningModel } {@link NaiveBayesModel } {@link NearestNeighborModel } {@link NeuralNetwork }
   * {@link RegressionModel } {@link RuleSetModel } {@link SequenceModel } {@link Scorecard } {@link
   * SupportVectorMachineModel } {@link TextModel } {@link TimeSeriesModel } {@link TreeModel }
   */
  List<IModel> getModel();

  /**
   * Gets the value of the extension property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extension property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Extension }
   */
  List<Extension> getExtension();

  /**
   * Gets the value of the version property.
   *
   * @return possible object is {@link String }
   */
  String getVersion();

  /**
   * Sets the value of the version property.
   *
   * @param value allowed object is {@link String }
   */
  void setVersion(String value);
}
