//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:12 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api;

import java.util.List;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Extension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Output" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}ModelStats" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}Targets" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}LocalTransformations" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}ResultField" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.dmg.org/PMML-4_4}RegressionTable" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="modelName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="functionName" use="required" type="{http://www.dmg.org/PMML-4_4}MINING-FUNCTION" /&gt;
 *       &lt;attribute name="algorithmName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="normalizationMethod" type="{http://www.dmg.org/PMML-4_4}REGRESSIONNORMALIZATIONMETHOD" default="none" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
public interface Regression {

  /**
   * Gets the value of the extension property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the extension property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Extension }
   */
  List<Extension> getExtension();

  /**
   * Gets the value of the output property.
   *
   * @return possible object is {@link Output }
   */
  Output getOutput();

  /**
   * Sets the value of the output property.
   *
   * @param value allowed object is {@link Output }
   */
  void setOutput(Output value);

  /**
   * Gets the value of the modelStats property.
   *
   * @return possible object is {@link ModelStats }
   */
  ModelStats getModelStats();

  /**
   * Sets the value of the modelStats property.
   *
   * @param value allowed object is {@link ModelStats }
   */
  void setModelStats(ModelStats value);

  /**
   * Gets the value of the targets property.
   *
   * @return possible object is {@link Targets }
   */
  Targets getTargets();

  /**
   * Sets the value of the targets property.
   *
   * @param value allowed object is {@link Targets }
   */
  void setTargets(Targets value);

  /**
   * Gets the value of the localTransformations property.
   *
   * @return possible object is {@link LocalTransformations }
   */
  LocalTransformations getLocalTransformations();

  /**
   * Sets the value of the localTransformations property.
   *
   * @param value allowed object is {@link LocalTransformations }
   */
  void setLocalTransformations(LocalTransformations value);

  /**
   * Gets the value of the resultField property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the resultField property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getResultField().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link ResultField }
   */
  List<ResultField> getResultField();

  /**
   * Gets the value of the regressionTable property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the regressionTable property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getRegressionTable().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link RegressionTable }
   */
  List<RegressionTable> getRegressionTable();

  /**
   * Gets the value of the modelName property.
   *
   * @return possible object is {@link String }
   */
  String getModelName();

  /**
   * Sets the value of the modelName property.
   *
   * @param value allowed object is {@link String }
   */
  void setModelName(String value);

  /**
   * Gets the value of the functionName property.
   *
   * @return possible object is {@link MININGFUNCTION }
   */
  MININGFUNCTION getFunctionName();

  /**
   * Sets the value of the functionName property.
   *
   * @param value allowed object is {@link MININGFUNCTION }
   */
  void setFunctionName(MININGFUNCTION value);

  /**
   * Gets the value of the algorithmName property.
   *
   * @return possible object is {@link String }
   */
  String getAlgorithmName();

  /**
   * Sets the value of the algorithmName property.
   *
   * @param value allowed object is {@link String }
   */
  void setAlgorithmName(String value);

  /**
   * Gets the value of the normalizationMethod property.
   *
   * @return possible object is {@link REGRESSIONNORMALIZATIONMETHOD }
   */
  REGRESSIONNORMALIZATIONMETHOD getNormalizationMethod();

  /**
   * Sets the value of the normalizationMethod property.
   *
   * @param value allowed object is {@link REGRESSIONNORMALIZATIONMETHOD }
   */
  void setNormalizationMethod(REGRESSIONNORMALIZATIONMETHOD value);
}
