//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.3.0
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.08.06 at 04:43:12 PM BST
//

package org.treblereel.gwt.xml.mapper.client.tests.pmml.model.api;

import java.math.BigInteger;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="i" type="{http://www.dmg.org/PMML-4_4}INT-NUMBER" /&gt;
 *       &lt;attribute name="j" type="{http://www.dmg.org/PMML-4_4}INT-NUMBER" /&gt;
 *       &lt;attribute name="theta" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
public interface Theta {

  /**
   * Gets the value of the i property.
   *
   * @return possible object is {@link BigInteger }
   */
  BigInteger getI();

  /**
   * Sets the value of the i property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  void setI(BigInteger value);

  /**
   * Gets the value of the j property.
   *
   * @return possible object is {@link BigInteger }
   */
  BigInteger getJ();

  /**
   * Sets the value of the j property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  void setJ(BigInteger value);

  /**
   * Gets the value of the theta property.
   *
   * @return possible object is {@link Double }
   */
  Double getTheta();

  /**
   * Sets the value of the theta property.
   *
   * @param value allowed object is {@link Double }
   */
  void setTheta(Double value);
}
